// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecode, NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProviderName(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EndpointUrl(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ModelName(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EnvironmentVariable(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GopassPath(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SecretFilePath(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectionDetail(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EnvironmentSecret(EnvironmentVariable);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GopassSecret(GopassPath);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct FileSecret(SecretFilePath);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum SecretSource {
    Environment(EnvironmentSecret),
    Gopass(GopassSecret),
    File(FileSecret),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProviderConfiguration {
    pub name: ProviderName,
    pub endpoint: EndpointUrl,
    pub default_model: ModelName,
    pub secret_source: SecretSource,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ConfigureProvider(ProviderConfiguration);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RetireProvider(ProviderName);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SetDefaultProvider(ProviderName);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Start {}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Stop {}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProviderConfigured(ProviderName);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProviderRetired(ProviderName);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DefaultProviderSet(ProviderName);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum LifecycleState {
    Started,
    Stopped,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Lifecycle(LifecycleState);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OrderRejectionReason {
    ProviderUnknown,
    ProviderAlreadyConfigured,
    EndpointInvalid,
    SecretUnavailable,
    PolicyStoreUnavailable,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct OrderRejection {
    pub reason: OrderRejectionReason,
    pub detail: RejectionDetail,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OperationKind {
    ConfigureProvider,
    RetireProvider,
    SetDefaultProvider,
    Start,
    Stop,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum UnimplementedReason {
    NotInPrototypeScope,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RequestUnimplemented {
    pub operation: OperationKind,
    pub reason: UnimplementedReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    ConfigureProvider(ConfigureProvider),
    RetireProvider(RetireProvider),
    SetDefaultProvider(SetDefaultProvider),
    Start(Start),
    Stop(Stop),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    ProviderConfigured(ProviderConfigured),
    ProviderRetired(ProviderRetired),
    DefaultProviderSet(DefaultProviderSet),
    Started(Lifecycle),
    Stopped(Lifecycle),
    OrderRejected(OrderRejection),
    RequestUnimplemented(RequestUnimplemented),
}

#[rustfmt::skip]
impl ProviderName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ProviderName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EndpointUrl {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for EndpointUrl {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ModelName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ModelName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EnvironmentVariable {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for EnvironmentVariable {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl GopassPath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for GopassPath {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SecretFilePath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for SecretFilePath {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RejectionDetail {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for RejectionDetail {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EnvironmentSecret {
    pub fn new(payload: EnvironmentVariable) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &EnvironmentVariable {
        &self.0
    }
    pub fn into_payload(self) -> EnvironmentVariable {
        self.0
    }
}
#[rustfmt::skip]
impl From<EnvironmentVariable> for EnvironmentSecret {
    fn from(payload: EnvironmentVariable) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl GopassSecret {
    pub fn new(payload: GopassPath) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &GopassPath {
        &self.0
    }
    pub fn into_payload(self) -> GopassPath {
        self.0
    }
}
#[rustfmt::skip]
impl From<GopassPath> for GopassSecret {
    fn from(payload: GopassPath) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl FileSecret {
    pub fn new(payload: SecretFilePath) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SecretFilePath {
        &self.0
    }
    pub fn into_payload(self) -> SecretFilePath {
        self.0
    }
}
#[rustfmt::skip]
impl From<SecretFilePath> for FileSecret {
    fn from(payload: SecretFilePath) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ConfigureProvider {
    pub fn new(payload: ProviderConfiguration) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ProviderConfiguration {
        &self.0
    }
    pub fn into_payload(self) -> ProviderConfiguration {
        self.0
    }
}
#[rustfmt::skip]
impl From<ProviderConfiguration> for ConfigureProvider {
    fn from(payload: ProviderConfiguration) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RetireProvider {
    pub fn new(payload: ProviderName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ProviderName {
        &self.0
    }
    pub fn into_payload(self) -> ProviderName {
        self.0
    }
}
#[rustfmt::skip]
impl From<ProviderName> for RetireProvider {
    fn from(payload: ProviderName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SetDefaultProvider {
    pub fn new(payload: ProviderName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ProviderName {
        &self.0
    }
    pub fn into_payload(self) -> ProviderName {
        self.0
    }
}
#[rustfmt::skip]
impl From<ProviderName> for SetDefaultProvider {
    fn from(payload: ProviderName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ProviderConfigured {
    pub fn new(payload: ProviderName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ProviderName {
        &self.0
    }
    pub fn into_payload(self) -> ProviderName {
        self.0
    }
}
#[rustfmt::skip]
impl From<ProviderName> for ProviderConfigured {
    fn from(payload: ProviderName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ProviderRetired {
    pub fn new(payload: ProviderName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ProviderName {
        &self.0
    }
    pub fn into_payload(self) -> ProviderName {
        self.0
    }
}
#[rustfmt::skip]
impl From<ProviderName> for ProviderRetired {
    fn from(payload: ProviderName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DefaultProviderSet {
    pub fn new(payload: ProviderName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ProviderName {
        &self.0
    }
    pub fn into_payload(self) -> ProviderName {
        self.0
    }
}
#[rustfmt::skip]
impl From<ProviderName> for DefaultProviderSet {
    fn from(payload: ProviderName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Lifecycle {
    pub fn new(payload: LifecycleState) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &LifecycleState {
        &self.0
    }
    pub fn into_payload(self) -> LifecycleState {
        self.0
    }
}
#[rustfmt::skip]
impl From<LifecycleState> for Lifecycle {
    fn from(payload: LifecycleState) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SecretSource {
    pub fn environment(payload: EnvironmentVariable) -> Self {
        Self::Environment(EnvironmentSecret::new(payload))
    }
    pub fn gopass(payload: GopassPath) -> Self {
        Self::Gopass(GopassSecret::new(payload))
    }
    pub fn file(payload: SecretFilePath) -> Self {
        Self::File(FileSecret::new(payload))
    }
}

#[rustfmt::skip]
impl Input {
    pub fn configure_provider(payload: ProviderConfiguration) -> Self {
        Self::ConfigureProvider(ConfigureProvider::new(payload))
    }
    pub fn retire_provider(payload: ProviderName) -> Self {
        Self::RetireProvider(RetireProvider::new(payload))
    }
    pub fn set_default_provider(payload: ProviderName) -> Self {
        Self::SetDefaultProvider(SetDefaultProvider::new(payload))
    }
    pub fn start(payload: Start) -> Self {
        Self::Start(payload)
    }
    pub fn stop(payload: Stop) -> Self {
        Self::Stop(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn provider_configured(payload: ProviderName) -> Self {
        Self::ProviderConfigured(ProviderConfigured::new(payload))
    }
    pub fn provider_retired(payload: ProviderName) -> Self {
        Self::ProviderRetired(ProviderRetired::new(payload))
    }
    pub fn default_provider_set(payload: ProviderName) -> Self {
        Self::DefaultProviderSet(DefaultProviderSet::new(payload))
    }
    pub fn started(payload: LifecycleState) -> Self {
        Self::Started(Lifecycle::new(payload))
    }
    pub fn stopped(payload: LifecycleState) -> Self {
        Self::Stopped(Lifecycle::new(payload))
    }
    pub fn order_rejected(payload: OrderRejection) -> Self {
        Self::OrderRejected(payload)
    }
    pub fn request_unimplemented(payload: RequestUnimplemented) -> Self {
        Self::RequestUnimplemented(payload)
    }
}

#[rustfmt::skip]
impl From<EnvironmentSecret> for SecretSource {
    fn from(payload: EnvironmentSecret) -> Self {
        Self::Environment(payload)
    }
}

#[rustfmt::skip]
impl From<GopassSecret> for SecretSource {
    fn from(payload: GopassSecret) -> Self {
        Self::Gopass(payload)
    }
}

#[rustfmt::skip]
impl From<FileSecret> for SecretSource {
    fn from(payload: FileSecret) -> Self {
        Self::File(payload)
    }
}

#[rustfmt::skip]
impl From<ConfigureProvider> for Input {
    fn from(payload: ConfigureProvider) -> Self {
        Self::ConfigureProvider(payload)
    }
}

#[rustfmt::skip]
impl From<RetireProvider> for Input {
    fn from(payload: RetireProvider) -> Self {
        Self::RetireProvider(payload)
    }
}

#[rustfmt::skip]
impl From<SetDefaultProvider> for Input {
    fn from(payload: SetDefaultProvider) -> Self {
        Self::SetDefaultProvider(payload)
    }
}

#[rustfmt::skip]
impl From<Start> for Input {
    fn from(payload: Start) -> Self {
        Self::Start(payload)
    }
}

#[rustfmt::skip]
impl From<Stop> for Input {
    fn from(payload: Stop) -> Self {
        Self::Stop(payload)
    }
}

#[rustfmt::skip]
impl From<ProviderConfigured> for Output {
    fn from(payload: ProviderConfigured) -> Self {
        Self::ProviderConfigured(payload)
    }
}

#[rustfmt::skip]
impl From<ProviderRetired> for Output {
    fn from(payload: ProviderRetired) -> Self {
        Self::ProviderRetired(payload)
    }
}

#[rustfmt::skip]
impl From<DefaultProviderSet> for Output {
    fn from(payload: DefaultProviderSet) -> Self {
        Self::DefaultProviderSet(payload)
    }
}

#[rustfmt::skip]
impl From<OrderRejection> for Output {
    fn from(payload: OrderRejection) -> Self {
        Self::OrderRejected(payload)
    }
}

#[rustfmt::skip]
impl From<RequestUnimplemented> for Output {
    fn from(payload: RequestUnimplemented) -> Self {
        Self::RequestUnimplemented(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ProviderName {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl EndpointUrl {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ModelName {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl EnvironmentVariable {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl GopassPath {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SecretFilePath {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RejectionDetail {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl EnvironmentSecret {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl GopassSecret {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl FileSecret {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SecretSource {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ProviderConfiguration {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ConfigureProvider {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RetireProvider {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SetDefaultProvider {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Start {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Stop {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ProviderConfigured {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ProviderRetired {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl DefaultProviderSet {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl LifecycleState {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Lifecycle {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl OrderRejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl OrderRejection {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl OperationKind {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl UnimplementedReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RequestUnimplemented {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_CONFIGURE_PROVIDER: u64 = 0x0000000000000000;
    pub const INPUT_RETIRE_PROVIDER: u64 = 0x0001000000000000;
    pub const INPUT_SET_DEFAULT_PROVIDER: u64 = 0x0002000000000000;
    pub const INPUT_START: u64 = 0x0003000000000000;
    pub const INPUT_STOP: u64 = 0x0004000000000000;
    pub const OUTPUT_PROVIDER_CONFIGURED: u64 = 0x0100000000000000;
    pub const OUTPUT_PROVIDER_RETIRED: u64 = 0x0101000000000000;
    pub const OUTPUT_DEFAULT_PROVIDER_SET: u64 = 0x0102000000000000;
    pub const OUTPUT_STARTED: u64 = 0x0103000000000000;
    pub const OUTPUT_STOPPED: u64 = 0x0104000000000000;
    pub const OUTPUT_ORDER_REJECTED: u64 = 0x0105000000000000;
    pub const OUTPUT_REQUEST_UNIMPLEMENTED: u64 = 0x0106000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    ConfigureProvider,
    RetireProvider,
    SetDefaultProvider,
    Start,
    Stop,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    ProviderConfigured,
    ProviderRetired,
    DefaultProviderSet,
    Started,
    Stopped,
    OrderRejected,
    RequestUnimplemented,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::ConfigureProvider(_) => InputRoute::ConfigureProvider,
            Self::RetireProvider(_) => InputRoute::RetireProvider,
            Self::SetDefaultProvider(_) => InputRoute::SetDefaultProvider,
            Self::Start(_) => InputRoute::Start,
            Self::Stop(_) => InputRoute::Stop,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::ConfigureProvider(_) => short_header::INPUT_CONFIGURE_PROVIDER,
            Self::RetireProvider(_) => short_header::INPUT_RETIRE_PROVIDER,
            Self::SetDefaultProvider(_) => short_header::INPUT_SET_DEFAULT_PROVIDER,
            Self::Start(_) => short_header::INPUT_START,
            Self::Stop(_) => short_header::INPUT_STOP,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_CONFIGURE_PROVIDER => Ok(InputRoute::ConfigureProvider),
            short_header::INPUT_RETIRE_PROVIDER => Ok(InputRoute::RetireProvider),
            short_header::INPUT_SET_DEFAULT_PROVIDER => {
                Ok(InputRoute::SetDefaultProvider)
            }
            short_header::INPUT_START => Ok(InputRoute::Start),
            short_header::INPUT_STOP => Ok(InputRoute::Stop),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::ProviderConfigured(_) => OutputRoute::ProviderConfigured,
            Self::ProviderRetired(_) => OutputRoute::ProviderRetired,
            Self::DefaultProviderSet(_) => OutputRoute::DefaultProviderSet,
            Self::Started(_) => OutputRoute::Started,
            Self::Stopped(_) => OutputRoute::Stopped,
            Self::OrderRejected(_) => OutputRoute::OrderRejected,
            Self::RequestUnimplemented(_) => OutputRoute::RequestUnimplemented,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::ProviderConfigured(_) => short_header::OUTPUT_PROVIDER_CONFIGURED,
            Self::ProviderRetired(_) => short_header::OUTPUT_PROVIDER_RETIRED,
            Self::DefaultProviderSet(_) => short_header::OUTPUT_DEFAULT_PROVIDER_SET,
            Self::Started(_) => short_header::OUTPUT_STARTED,
            Self::Stopped(_) => short_header::OUTPUT_STOPPED,
            Self::OrderRejected(_) => short_header::OUTPUT_ORDER_REJECTED,
            Self::RequestUnimplemented(_) => short_header::OUTPUT_REQUEST_UNIMPLEMENTED,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_PROVIDER_CONFIGURED => {
                Ok(OutputRoute::ProviderConfigured)
            }
            short_header::OUTPUT_PROVIDER_RETIRED => Ok(OutputRoute::ProviderRetired),
            short_header::OUTPUT_DEFAULT_PROVIDER_SET => {
                Ok(OutputRoute::DefaultProviderSet)
            }
            short_header::OUTPUT_STARTED => Ok(OutputRoute::Started),
            short_header::OUTPUT_STOPPED => Ok(OutputRoute::Stopped),
            short_header::OUTPUT_ORDER_REJECTED => Ok(OutputRoute::OrderRejected),
            short_header::OUTPUT_REQUEST_UNIMPLEMENTED => {
                Ok(OutputRoute::RequestUnimplemented)
            }
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &[
        "ConfigureProvider",
        "RetireProvider",
        "SetDefaultProvider",
        "Start",
        "Stop",
    ];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        self.short_header()
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::ExchangeFrame<Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let request = signal_frame::Request::from_payload(self);
        Frame::with_short_header(
            short_header,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::with_short_header(
            short_header,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
}
